services:
  mariadb:
    image: bitnami/mariadb:11.5.2
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: moodle
      MARIADB_USER: moodle
      MARIADB_PASSWORD: moodle
    volumes:
      - mariadb_data:/bitnami/mariadb
  phpmyadmin:
    image: bitnami/phpmyadmin:5.2.1
    restart: always
    environment:
      MAX_EXECUTION_TIME: 600
      MEMORY_LIMIT: 512M
      UPLOAD_LIMIT: 512M
      DATABASE_HOST: mariadb
      DATABASE_USER: moodle
      DATABASE_PASSWORD: moodle
    ports:
      - 8080:8080
    depends_on:
      - mariadb
  moodle:
    image: bitnami/moodle:4.5
    restart: always
    environment:
      BITNAMI_DEBUG: true
      MOODLE_DATABASE_HOST: mariadb
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_PASSWORD: moodle
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_ROOT_PASSWORD: root
      MOODLE_USERNAME: moodle
      MOODLE_PASSWORD: moodle
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 8081:8080
    depends_on:
      - mariadb
    volumes:
      - ./moodle_data:/bitnami/moodle
      - ./moodledata_data:/bitnami/moodledata

volumes:
  mariadb_data:
